name: CI
on:
  schedule:
    # Run every Monday at 9:00 AM
    - cron: "0 9 * * 1"
  push:
    # This will trigger the workflow on every push to any branch. 
    # If you want to restrict it to specific branches, you can list them as before.
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
