name: Check Markdown Links
on:
  pull_request:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight every day

jobs:
  lychee:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for dead links in Markdown files
      uses: lycheeverse/lychee-action@v2
      with:
        args: --verbose --no-progress --timeout 60 --max-retries 3 --retry-wait-time 5 --max-concurrency 100 --accept 200..=299,403,429,500,503 './**/*.md'
